import json
import os
from typing import TypedDict, Dict, Any, List
from langgraph.graph import StateGraph, END
from langchain_groq import ChatGroq
from langchain_core.messages import SystemMessage, HumanMessage
import streamlit as st
from dotenv import load_dotenv

load_dotenv()

from src.rag import retrieve_guidelines

class AgentState(TypedDict):
    patient_data: Dict[str, Any]
    risk_summary: str
    retrieved_guidelines: str
    final_report: Dict[str, Any]
    error: str

# Node Functions

def analyze_risk(state: AgentState) -> AgentState:
    try:
        data = state.get("patient_data", {})
        total_high = data.get("total_high_risk", 0)
        avg_prob = data.get("avg_probability", 0.0)
        common_factors = data.get("common_factors", [])
        
        summary = (
            f"The dataset contains {total_high} high-risk patients. "
            f"The average no-show probability for this group is {avg_prob:.2f}. "
            f"Key demographic and historical patterns observed include: {', '.join(common_factors)}."
        )
        return {"risk_summary": summary}
    except Exception as e:
        return {"error": str(e)}

def retrieve_guidelines_node(state: AgentState) -> AgentState:
    try:
        guidelines = retrieve_guidelines()
        return {"retrieved_guidelines": guidelines}
    except Exception as e:
        return {"error": str(e)}

def generate_report(state: AgentState) -> AgentState:
    try:
        if "error" in state and state["error"]:
            return state

        risk_summary = state.get("risk_summary", "")
        guidelines = state.get("retrieved_guidelines", "")

        # Check API key from env or st.secrets
        api_key = os.environ.get("GROQ_API_KEY")
        if not api_key:
            if "GROQ_API_KEY" in st.secrets:
                api_key = st.secrets["GROQ_API_KEY"]
            else:
                return {"error": "GROQ_API_KEY missing in .env or Streamlit secrets"}

        llm = ChatGroq(
            api_key=api_key,
            model_name="llama-3.1-8b-instant",
            temperature=0.2, # Low temperature for structured output
        )

        sys_msg = SystemMessage(
            content=(
                "You are a clinical care coordination expert. Generate evidence-based, "
                "actionable intervention reports. Always be specific, concise, and ethical. "
                "Never make up patient data. Always include disclaimers that recommendations "
                "are advisory only and must be reviewed by qualified medical professionals."
            )
        )
        
        user_prompt = (
            "Based on the following risk analysis and guidelines, generate a structured "
            "care coordination report in valid JSON format with exactly these keys:\n"
            "{\n"
            "  \"risk_summary\": \"2-3 sentence summary of the appointment risk landscape\",\n"
            "  \"contributing_factors\": [\"factor1\", \"factor2\", \"factor3\", \"factor4\", \"factor5\"],\n"
            "  \"intervention_strategies\": [\n"
            "    {\"strategy\": \"name\", \"description\": \"details\", \"priority\": \"High/Medium/Low\"}\n"
            "  ],\n"
            "  \"sources\": [\"source1\", \"source2\", \"source3\"],\n"
            "  \"operational_disclaimer\": \"operational disclaimer text\",\n"
            "  \"ethical_disclaimer\": \"ethical disclaimer text\"\n"
            "}\n\n"
            f"Risk Analysis: {risk_summary}\n"
            f"Guidelines: {guidelines}\n\n"
            "Return ONLY valid JSON. No markdown, no backticks, no explanation."
        )

        response = llm.invoke([sys_msg, HumanMessage(content=user_prompt)])
        
        # Clean response to parse JSON
        content = response.content.strip()
        if content.startswith("```json"):
            content = content[7:]
        if content.startswith("```"):
            content = content[3:]
        if content.endswith("```"):
            content = content[:-3]
        content = content.strip()

        report_dict = json.loads(content)
        return {"final_report": report_dict}

    except Exception as e:
        return {"error": str(e)}

def append_disclaimer(state: AgentState) -> AgentState:
    if "error" in state and state["error"]:
        return state
        
    report = state.get("final_report", {})
    if not report:
        report = {}
        
    operational_fallback = (
        "This report is generated by an AI system and is intended for "
        "operational planning purposes only. Clinical staff must review all recommendations."
    )
    ethical_fallback = (
        "Patient privacy must be maintained. All interventions must comply with "
        "local healthcare regulations. This system does not replace clinical judgment."
    )

    if not "operational_disclaimer" in report or not report["operational_disclaimer"]:
        report["operational_disclaimer"] = operational_fallback
    if not "ethical_disclaimer" in report or not report["ethical_disclaimer"]:
        report["ethical_disclaimer"] = ethical_fallback

    return {"final_report": report}

def build_agent():
    workflow = StateGraph(AgentState)
    
    workflow.add_node("analyze_risk", analyze_risk)
    workflow.add_node("retrieve_guidelines", retrieve_guidelines_node)
    workflow.add_node("generate_report", generate_report)
    workflow.add_node("append_disclaimer", append_disclaimer)
    
    workflow.set_entry_point("analyze_risk")
    workflow.add_edge("analyze_risk", "retrieve_guidelines")
    workflow.add_edge("retrieve_guidelines", "generate_report")
    workflow.add_edge("generate_report", "append_disclaimer")
    workflow.add_edge("append_disclaimer", END)
    
    return workflow.compile()
