from fpdf import FPDF
from datetime import datetime

class ReportPDF(FPDF):
    def header(self):
        # Header - generated text
        self.set_font('helvetica', 'B', 15)
        self.cell(0, 10, 'Clinical Care Coordination Report', 0, 1, 'C')
        self.set_font('helvetica', 'I', 10)
        self.cell(0, 10, f'Generated on: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}', 0, 1, 'C')
        self.ln(10)

    def footer(self):
        # Footer
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.cell(0, 10, 'Generated by Clinical No-Show AI System | Advisory Only', 0, 0, 'C')

def generate_pdf_report(report_data: dict) -> bytes:
    """
    Generate a clean PDF byte string from the structured report dictionary.
    """
    pdf = ReportPDF()
    pdf.add_page()
    pdf.set_font('helvetica', '', 11)
    
    # 1. Risk Summary
    pdf.set_font('helvetica', 'B', 12)
    pdf.cell(0, 10, 'Risk Summary', 0, 1)
    pdf.set_font('helvetica', '', 11)
    pdf.write(7, report_data.get('risk_summary', 'N/A'))
    pdf.ln(10)
    
    # 2. Contributing Factors
    pdf.set_font('helvetica', 'B', 12)
    pdf.cell(0, 10, 'Key Contributing Factors', 0, 1)
    pdf.set_font('helvetica', '', 11)
    for factor in report_data.get('contributing_factors', []):
        pdf.write(7, f"- {factor}\n")
    pdf.ln(5)
    
    # 3. Intervention Strategies
    pdf.set_font('helvetica', 'B', 12)
    pdf.cell(0, 10, 'Intervention Strategies', 0, 1)
    for strategy in report_data.get('intervention_strategies', []):
        name = strategy.get('strategy', 'Unknown')
        desc = strategy.get('description', '')
        priority = strategy.get('priority', 'Medium')
        
        pdf.set_font('helvetica', 'B', 11)
        pdf.write(7, f"> {name} ({priority} Priority)\n")
        pdf.set_font('helvetica', '', 11)
        pdf.write(7, f"{desc}\n")
        pdf.ln(3)
    pdf.ln(2)
        
    # 4. Sources
    pdf.set_font('helvetica', 'B', 12)
    pdf.cell(0, 10, 'Sources & References', 0, 1)
    pdf.set_font('helvetica', '', 11)
    for i, source in enumerate(report_data.get('sources', []), 1):
        pdf.write(7, f"{i}. {source}\n")
    pdf.ln(5)
    
    # 5. Disclaimers
    pdf.set_font('helvetica', 'B', 12)
    pdf.cell(0, 10, 'Disclaimers', 0, 1)
    pdf.set_font('helvetica', 'I', 10)
    pdf.write(6, "Operational: " + report_data.get('operational_disclaimer', ''))
    pdf.ln(8)
    pdf.write(6, "Ethical: " + report_data.get('ethical_disclaimer', ''))
    
    return bytes(pdf.output())
